version: "3"
services: 
 itr-nginx:
  image: itr-nginx-container
  container_name: itr-nginx
  volumes:
   - /data/ITR-data/nginx/certificates:/etc/nginx/ssl:z
   - /data/ITR-webclient/:/usr/share/nginx/html:z
  ports: 
   - 80:80
   - 443:443
  restart: always
  networks: 
   - itr-network
  depends_on:
   - itr-api
   - itr-public-api
   - itr-postgresql

 itr-api:
  image: itr-internal-api-container
  container_name: itr-api
  volumes:
   - /data/ITR-API:/etc/ITR/API:z
   - /data/ITR-public-API:/etc/ITR/Public-API:z
   - /data/ITR-API/instance/application.cfg:/data/ITR-data/instance/application.cfg:z
   - /data/ITR-API/instance/log:/data/ITR-data/instance/log/internal:z
   - /data/ITR-API/instance/translations:/data/ITR-data/instance/translations:z
   - /data/ITR-API/instance/media:/data/ITR-data/instance/media:z
   - /data/ITR-API/instance/cache:/data/ITR-data/instance/cache:z
  environment:
   - ITRPORT=80
   - ITRTHREADS=75
  restart: always
  networks:
   - itr-network
  depends_on:
   - itr-postgresql   

 itr-public-api:
  image: itr-external-api-container
  container_name: itr-public-api
  volumes:
   - /data/ITR-API:/etc/ITR/API:z
   - /data/ITR-public-API:/etc/ITR/Public-API:z
   - /data/ITR-API/instance/application.cfg:/data/ITR-data/instance/application.cfg:z
   - /data/ITR-API/instance/log:/data/ITR-data/instance/log/external:z
   - /data/ITR-API/instance/translations:/data/ITR-data/instance/translations:z
   - /data/ITR-API/instance/media:/data/ITR-data/instance/media:z
   - /data/ITR-API/instance/cache:/data/ITR-data/instance/cache:z
  environment:
   - ITRPORT=80
   - ITRTHREADS=5
  restart: always
  networks:
   - itr-network
  depends_on:
   - itr-postgresql   

 itr-postgresql:
  image: itr-postgres-container
  container_name: itr-postgresql
  volumes:
   - /data/ITR-data/database:/var/lib/postgresql/data:z
   - /data/ITR-data/database/backup:/backup:z  
  restart: always
  environment:
   - PG_PASSWORD=${PG_PASSWORD}  
  networks:
   - itr-network

networks:
  itr-network:
    driver: bridge
