version: "3"
services:
 itr-nginx:
  image: itr-nginx-container
  container_name: itr-nginx
  volumes:
   - /data/ITR-data/nginx/certificates:/etc/nginx/ssl:z
   - /data/ITR-webclient/:/usr/share/nginx/html:z
  ports:
   - 80:80
   - 443:443
  restart: always
  environment:
   - WWW=${WWW}
  networks:
   - itr-network
  command: sh -c "crond && nginx -g 'daemon off;'" 
  depends_on:
   - itr-api
   - itr-public-api
   - itr-postgresql
  ulimits:
    nproc: 65535
    nofile:
      soft: 32000
      hard: 60000

 itr-api:
  image: itr-internal-api-container
  container_name: itr-api
  volumes:
   - /data/ITR-API:/etc/ITR/API:z
   - /data/ITR-public-API:/etc/ITR/Public-API:z
   - /data/ITR-data/instance/application.cfg:/etc/ITR/API/instance/application.cfg:z
   - /data/ITR-data/instance/log/internal:/etc/ITR/API/instance/log:z
   - /data/ITR-data/instance/translations:/etc/ITR/API/instance/translations:z
   - /data/ITR-data/instance/media:/etc/ITR/API/instance/media:z
   - /data/ITR-data/instance/cache:/etc/ITR/API/instance/cache:z
   - /data/ITR-webclient/:/usr/share/nginx/html:z
  environment:
   - ITRPORT=80
   - ITRTHREADS=40
  restart: always
  networks:
   - itr-network
  depends_on:
   - itr-postgresql
  ulimits:
    nproc: 65535
    nofile:
      soft: 32000
      hard: 60000

 itr-public-api:
  image: itr-external-api-container
  container_name: itr-public-api
  volumes:
   - /data/ITR-API:/etc/ITR/API:z
   - /data/ITR-public-API:/etc/ITR/Public-API:z
   - /data/ITR-data/instance/application.cfg:/etc/ITR/API/instance/application.cfg:z
   - /data/ITR-data/instance/log/external:/etc/ITR/API/instance/log:z
   - /data/ITR-data/instance/translations:/etc/ITR/API/instance/translations:z
   - /data/ITR-data/instance/media:/etc/ITR/API/instance/media:z
   - /data/ITR-data/instance/cache:/etc/ITR/API/instance/cache:z
   - /data/ITR-webclient/:/usr/share/nginx/html:z
  environment:
   - ITRPORT=80
   - ITRTHREADS=5
  restart: always
  networks:
   - itr-network
  depends_on:
   - itr-postgresql
  ulimits:
    nproc: 65535
    nofile:
      soft: 32000
      hard: 60000

 itr-postgresql:
  image: itr-postgres-container
  container_name: itr-postgresql
  volumes:
   - /data/ITR-data/database/data:/var/lib/postgresql/data:z
   - /data/ITR-data/database/backup:/backup:z
  restart: always
  ports:
   - ${PG_IP}:25432:5432  
  environment:
   - PG_PASSWORD=${PG_PASSWORD}
  networks:
   - itr-network
  ulimits:
    nproc: 65535
    nofile:
      soft: 32000
      hard: 60000

networks:
  itr-network:
    driver: bridge
